sudo: false
language: java
install:
  - mvn clean install -Dmaven.test.skip=true | egrep -v '(Downloading:|Downloaded:)'
script: 
  - mvn clean install -rf :org.wso2.carbon.registry.test.smoke
  - mvn clean install -rf :org.wso2.carbon.registry.test.soapservice
  - mvn clean install -rf :org.wso2.carbon.registry.test.smoke
  - mvn clean install -rf :org.wso2.carbon.registry.test.extensibility
jdk:
  - oraclejdk7
branches:
  only:
    - travisCIBuild